%YAML 1.2
---
run_duration:
  description: Simulation run time
  value:
    type: float
    default: 1.
    units: s
    range:
      min: 0
      max: 1000000
---
thermal_diffusivity:
  name: Thermal diffusivity
  description: Thermal diffusivity
  value:
    type: float
    default: 1.
    range:
      min: 0.0
      max: 10.0
    units: m^2/s
---
number_of_rows:
  name: Number of rows
  description: Number of grid rows.
  value:
    type: int
    default: 10
    range:
      min: 0
      max: 1000
    units: -

number_of_columns:
  name: Number of columns
  description: Number of grid columns.
  value:
    type: int
    default: 10
    range:
      min: 0
      max: 1000
    units: -
