name: Build/Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: true

      - name: Show conda installation info
        run: conda info

      - name: Install dependencies
        run: |
          conda install --file=requirements.txt -c conda-forge
          conda list

      - name: Build and install package
        run: pip install .

      - name: Install testing dependencies
        run: conda install --file=requirements-testing.txt -c conda-forge

      - name: Test
        run: |
          pytest --cov=heat --cov-report=xml:./coverage.xml -vvv
          bmi-test heat:BmiHeat --config-file=./examples/heat.yaml --root-dir=./examples -vvv

      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint
        run: |
          pip install flake8
          make lint
