name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Build and install package
        run: pip install -e .[testing]

      - name: Test
        run: |
          pytest --cov=heat --cov-report=xml:./coverage.xml -vvv
          bmi-test heat:BmiHeat --config-file=./examples/heat.yaml --root-dir=./examples -vvv

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: AndreMiras/coveralls-python-action@develop
